### ISSUE TITLE
502 Bad Gateway accessing Cyberbay website with Lighthouse VPN

### ISSUE THREAD

**Issue by amela-uyen** [Reimagine-Cyberbay/roadmap#1]
**Before you start, have you tried to search for similar issues?**
- [x] Yes, I have tried to search for similar issues and couldn't find one.

**Security related issues**
If this is a security related issue, please submit it via our [official bug bounty program](https://community.cyberbay.tech/signin/bounty-hunter?target=/bounty/detail/2NoGzq7RoBLa8Is_pkLq) instead. We offer a proper bug bounty program there.

## Describe the bug
502 Bad Gateway error shown after connecting Cyberbay Lighthouse, followed by visiting Cyberbay website https://cyberbay.tech

## Steps to reproduce
1. Login valid bounty hunter account
2. Enroll in any mission
3. Connect to lighthouse VPN
4. Access https://cyberbay.tech

## Expected behavior
Website loaded successfully.

## Screenshots
![Image 2024-04-09 at 6 36 20 PM](https://github.com/Reimagine-Cyberbay/roadmap/assets/166580873/08cad5e0-3ccb-42d7-9b93-857b585cc74b)

## Environment
**Date**: 2024-04-09
**OS/Browser version**: Any

### Appreciation
We appreciate your contribution and patience. If you are a platform bounty hunter and would not mind to share, please input your platform display name below and we will see what we can do:
<Enter your display name here, if applicable>

**Comment by cyberbay-louischoi** [comment]
Bug confirmed.

**Comment by cyberbay-louischoi** [comment]
Fixed in latest deployment on 15 Apr, 2024
